---
  - name: 패키지 설치 - {{ packages }}
    yum:
      name: "{{ packages }}"
      state: latest

  - name: 서비스 기동 - {{ service }}
    service:
      name: "{{ service }}"
      enabled: true
      state: started

