---
- name: Restore the playbooks. 
  hosts: all
  vars_files: vars.yml
  gather_facts: no
  tasks:
   # 1) 파일 삭제 
  #   - /etc/pki/*
  #   - /var/www/html/*
    - name: 파일 삭제  - /etc/pki/*, /var/www/html/*
      file:
        path: "{{ item.dest }}"
        state: absent
      loop: "{{ web_config_files }}"

  # 2) 서비스 종료 
  #   - httpd
    - name: 서비스 종료 - httpd
      service: 
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes
  # 3) 패키지 삭제 
  #   - httpd
  #   - mod_ssl
    - name: 패키지 삭제 - httpd, mod_ssl
      yum:
        name: "{{ packages }}"
        state: absent
  # 4) 방화벽 포트 제거 
  #   - http
  #   - https
    - name: 방화벽 포트 제거 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: no
        immediate: no
        state: disabled
      with_items: "{{ fw_port }}"