min_ram_mb: 256
packages: 
  - httpd
  - mod_ssl
services:
  - httpd
  - firewalld
ssl_dir: 
  - /etc/pki/tls/private
  - /etc/pki/tls/certs
web_config_files: 
  - src: files/localhost.crt
    dest: /etc/pki/tls/certs/localhost.crt
  - src: files/localhost.key
    dest: /etc/pki/tls/private/localhost.key
  - src: files/index.html
    dest: /var/www/html/index.html
web_service: httpd
fw_port: 
  - http
  - https 