---
- name: Restore playbook.yml
  hosts: all
  tasks:
    # /var/www/html/index.html 파일 삭제
    - name: index 파일 삭제 
      file: 
        path: /var/www/html/index.html
        state: absent

    # 방화벽 포트 닫기 - http
    - name: 방화벽 포트 닫기 - http
      firewalld:
        service: http
        permanent: yes
        state: disabled
        immediate: yes

    # 패키지 삭제 - httpd, mariadb-server
    - name: 패키지 삭제 - httpd, mariadb-server
      yum: 
        name:
          - httpd
          - mariadb-server
        state: absent

    # 팩트 삭제 - /etc/ansible/facts.d 삭제
    - name: 팩트 삭제 - /etc/ansible/facts.d
      file:
        path: /etc/ansible/facts.d
        state: absent